spring:
 application:
   name: helloservice
   #sets the application name for our Eureka client
server:
     port: 8094
eureka:
  client:
    register-with-eureka: true
 #service must needed to resiter in registry service so register eureka=true
    fetch-registry: true
#we want to fetch the service from registry therefore fetch =true
    service-url:
         defaultZone: http://localhost:8761/eureka
#where registry runs
  instance: 
    hostname: localhost   
